name: x_store
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - res/images/
    - res/icons/

  fonts:
    - family: Gilroy
      fonts:
        - asset: res/fonts/Gilroy/Gilroy-Thin.otf
          weight: 100
        - asset: res/fonts/Gilroy/Gilroy-UltraLight.otf
          weight: 200
        - asset: res/fonts/Gilroy/Gilroy-Light.otf
          weight: 300
        - asset: res/fonts/Gilroy/Gilroy-Regular.otf
          weight: 400
        - asset: res/fonts/Gilroy/Gilroy-Medium.otf
          weight: 500
        - asset: res/fonts/Gilroy/Gilroy-SemiBold.otf
          weight: 600
        - asset: res/fonts/Gilroy/Gilroy-Bold.otf
          weight: 700
        - asset: res/fonts/Gilroy/Gilroy-Extrabold.otf
          weight: 800
        - asset: res/fonts/Gilroy/Gilroy-Black.otf
          weight: 900

    - family: Poppins
      fonts:
        - asset: res/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: res/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: res/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: res/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: res/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: res/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: res/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: res/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: res/fonts/Poppins/Poppins-Black.ttf
          weight: 900
